version: '3.4'

services:
  sma.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "StaticFile:Domain=https://api.thanghieu.online"
    ports: 
      - "3003:80"
    volumes:
      - media_netcore:/images
volumes:
  media_netcore: